# -*- coding: utf-8 -*-
"""logger_setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OjNgVjmYgCZ0Kz8rHv5BBKLfk3ZX59YU
"""

import logging

def setup_logging(log_file):
    logging.getLogger(__name__)
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s : %(message)s',
        handlers=[
            logging.FileHandler(log_file),  # Log to file
            logging.StreamHandler()  # Log to console
        ]
    )

import os

log_file = os.path.join("../logs", "pipeline.log")
setup_logging(log_file)